trigger:
- CICD-Pipeline

pool:
  vmImage: ubuntu-latest

variables:
    imageName: 'MatchMakerUI'

steps:
# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     repository: $(imageName)
#     command: build
#     Dockerfile: app/Dockerfile
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: $(imageName)
    containerRegistry: $(dockerRegistryServiceConnection)
    Dockerfile: '**/Dockerfile'